blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/valgaze/speedybot-mini/discussions
    about: Start discussion for help deployment, performance, analytics, conversation design, etc
  - name: 🔧🤖 Speedybot Garage
    url: https://codepen.io/valgaze/full/MWVjEZV
    about: Add/remove webhooks, test Adaptive Cards, manage rooms and more (source-code available in editor)
